cache: bundler
language: ruby
rvm:
  - 2.1.7
script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
notifications:
  email: false