before_script: bundle update
language: ruby
rvm:
  - 2.1.7
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  notifications:
    email: false