# Site settings
title: "Jason's classroom"
email: support@jasonsclassroom.com
description: > 
  A place to study for your High School Equivalency Diploma
  
baseurl: ""
url: http://www.jasonsclassroom.com
repository: champa720/hse-materialize

google_analytics: UA-60117774-1

social_media:
  facebook: http://www.facebook.com/groups/jasonsclassroom
  linkedin: https://www.linkedin.com/in/jason-kilpatrick-17111717
  github: https://github.com/champa720/hse-materialize


# Build settings
timezone: America/Denver
markdown: kramdown
kramdown:
  math_engine: mathjax
# theme: minima
gems:
  - jekyll-feed
  - jekyll-github-metadata
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed


# Collections & Defaults
collections:
  pages:
    output: true
    permalink: /:path/
  hse:
    output: true
  chapters:
    output: true
    permalink: /study/:path/
  sections:
    output: true
    permalink: /study/:path/

defaults:
  # HSE Defaults
  -
    scope:
      path: "_hse/ged"
      type: "hse"
    values:
      category: GED
  -
    scope:
      path: "_hse/hiset"
      type: "hse"
    values:
      category: HiSET
      
  # Study Materials
  -
    scope:
      path: "_chapters"
      type: "chapters"
    values:
      layout: chapter
  -
    scope:
      path: "_sections"
      type: "sections"
    values:
      layout: section
      
  # Subject Defaults
  -
    scope:
      path: "/reading"
      type: "reading"
    values:
      subject: reading
  -
    scope:
      path: "writing"
    values:
      subject: writing
      
  # Volume Defaults
  -
    scope:
      path: "/reading/achieve"
    values:
      category: Common Core Achieve
  -
    scope:
      path: "/reading/basics"
    values:
      category: Common Core Basics
  -
    scope:
      path: "/writing/achieve"
    values:
      category: Common Core Achieve
  -
    scope:
      path: "/writing/basics"
    values:
      category: Common Core Basics