# Site settings
title: "Jason's classroom"
email: support@jasonsclassroom.com
description: > 
  A place to study for your High School Equivalency Diploma
  
baseurl: ""
url: "http://www.jasonsclassroom.com"
repository: champa720/hse-materialize

timezone: America/Denver

social:
  - name: facebook
    tooltip: join my private study group
    url: "http://www.facebook.com/groups/jasonsclassroom"
  - name: github
    tooltip: see my code
    url: "https://github.com/champa720/hse-materialize"
  - name: linkedin
    tooltip: network
    url: "https://www.linkedin.com/in/jason-kilpatrick-17111717"
  # - name: rss url:
  # - name: twitter url:
  # - name: dropbox url:
  # - name: google-plus url:

# Build settings
markdown: kramdown
exclude: [vendor]

collections:
  # xyz
  cde:
    output: true
    categories: "instructor resources"
    image_path: /assets/img/cde-shield-1x.png
    permalink: /resources/:collection/:path
  curriculum:
    output: true
    categories: "instructor resources"
    icon: description
    color: grey
    permalink: /resources/:collection/:path
  posts:
    output: true
    categories: "instructor resources"
    icon: chrome_reader_mode
    color: grey
    permalink: /resources/:collection/:path
    
  # hse exams
  ged:
    output: true
    categories: "hse exams"
    image_path: /assets/img/ged-logo-1x.png
    tagline: Welcome to the first step towards your dreams
    permalink: /hse/:collection/:path
  hiset:
    output: true
    categories: "hse exams"
    image_path: /assets/img/hiset-logo-1x.png
    tagline: Now there’s a choice in High School Equivalency Tests
    permalink: /hse/:collection/:path
  tasc:
    output: true
    categories: "hse exams"
    image_path: /assets/img/tasc-logo-1x.png
    tagline: The New National High School Equivalency Exam
    permalink: /hse/:collection/:path
    
  # study materials
  mathematics:
    output: true
    categories: "study materials"
    icon: widgets
    color: orange
    permalink: /materials/:collection/:path
  reading:
    output: true
    categories: "study materials"
    icon: book
    color: blue
    permalink: /materials/:collection/:path
  science:
    output: true
    categories: "study materials"
    icon: lightbulb_outline
    color: purple
    permalink: /materials/:collection/:path
  social-studies:
    output: true
    categories: "study materials"
    icon: account_balance
    color: green
    permalink: /materials/:collection/:path
  writing:
    output: true
    categories: "study materials"
    icon: edit
    color: red
    permalink: /materials/:collection/:path

defaults:
  - scope:
      path: ""
    values:
      layout: page
      author: jason
      color: deep-purple
  - scope:
      type: cde
    values:
      layout: page_alt
      category: Instructor Resources
      image_path: /assets/img/cde-shield-1x.png
  - scope:
      type: curriculum
    values:
      layout: iframe
  # pages
  - scope:
      path: "hse"
    values:
      categories: hse exams
  - scope:
      path: "materials"
    values:
      categories: study materials
  - scope:
      path: "resources"
    values:
      categories: instructor resources
  
  # hse exams  
  - scope:
      path: "_ged"
    values:
      layout: page_alt
      category: HS Equivalency Exams
      tagline: Welcome to the first step towards your dreams
      image_path: /assets/img/ged-logo-1x.png
  - scope:
      path: "_hiset"
    values:
      layout: page_alt
      category: HS Equivalency Exams
      tagline: Now there’s a choice in High School Equivalency Tests
      image_path: /assets/img/hiset-logo-1x.png
  - scope:
      path: "_tasc"
    values:
      layout: page_alt
      category: HS Equivalency Exams
      tagline: The New National High School Equivalency Exam
      image_path: /assets/img/tasc-logo-1x.png
      
  # materials
  - scope:
      path: "_mathematics"
    values:
      color: orange
      icon: widgets
  - scope:
      path: "_mathematics/cc-basics"
    values:
      category: cc-basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      image_path: /assets/img/book_covers/ccb-mathematics.jpg
  - scope:
      path: "_mathematics/khan-academy"
    values:
      category: khan-academy
      tagline: You can learn anything!
      image_path: /assets/img/ka-logo-5x.png
  - scope:
      path: "_reading"
    values:
      color: blue
      icon: book
  - scope:
      path: "_reading/cc-basics"
    values:
      category: cc-basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      image_path: /assets/img/book_covers/ccb-reading.jpg
  - scope:
      path: "_science"
    values:
      color: purple
      icon: lightbulb_outline
  - scope:
      path: "_science/cc-basics"
    values:
      category: cc-basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      image_path: /assets/img/book_covers/ccb-science.jpg
  - scope:
      path: "_science/cc-achieve"
    values:
      category: cc-achieve
      tagline: Mastering Essential Test Readiness Skills for High School Equivalency Exams
      image_path: /assets/img/book_covers/cca-science.jpg
  - scope:
      path: "_social-studies"
    values:
      color: green
      icon: account_balance
  - scope:
      path: "_social-studies/cc-basics"
    values:
      category: cc-basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      image_path: /assets/img/book_covers/ccb-social-studies.jpg
  - scope:
      path: "_social-studies/cc-achieve"
    values:
      category: cc-achieve
      tagline: Mastering Essential Test Readiness Skills for High School Equivalency Exams
      image_path: /assets/img/book_covers/cca-social-studies.jpg
  - scope:
      path: "_writing"
    values:
      color: red
      icon: edit
  - scope:
      path: "_writing/cc-achieve"
    values:
      category: cc-achieve
      tagline: 
      image_path: 