# Site settings
title: "Jason's classroom"
email: support@jasonsclassroom.com
description: > 
  A place to study for your High School Equivalency Diploma
  
baseurl: ""
url: "http://www.jasonsclassroom.com"
repository: champa720/hse-materialize

timezone: America/Denver

social:
  - name: facebook
    tooltip: join my private study group
    url: "http://www.facebook.com/groups/jasonsclassroom"
  - name: github
    tooltip: see my code
    url: "https://github.com/champa720/hse-materialize"
  - name: linkedin
    tooltip: network
    url: "https://www.linkedin.com/in/jason-kilpatrick-17111717"
  # - name: rss url:
  # - name: twitter url:
  # - name: dropbox url:
  # - name: google-plus url:

# Build settings
markdown: kramdown
exclude: [vendor]
sass:
  style: compressed

collections:
  # instructor resources
  cde:
    output: true
    category: Instructor Resources
    image_path: /assets/img/cde-shield-1x.png
    permalink: /resources/:collection/:path
  curriculum:
    output: true
    category: Instructor Resources
    icon: description
    color: grey
    permalink: /resources/:collection/:path
  posts:
    output: true
    category: Instructor Resources
    icon: chrome_reader_mode
    color: grey
    permalink: /resources/:collection/:path
    
  # hse exams
  ged:
    output: true
    category: HS Equivalency Exams
    image_path: /assets/img/ged-logo-1x.png
    tagline: Welcome to the first step towards your dreams
    permalink: /hse/:collection/:path
  hiset:
    output: true
    category: HS Equivalency Exams
    image_path: /assets/img/hiset-logo-1x.png
    tagline: Now there’s a choice in High School Equivalency Tests
    permalink: /hse/:collection/:path
  tasc:
    output: true
    category: HS Equivalency Exams
    image_path: /assets/img/tasc-logo-1x.png
    tagline: The New National High School Equivalency Exam
    permalink: /hse/:collection/:path
    
  # study materials
  mathematics:
    output: true
    category: Study Materials
    icon: widgets
    color: orange
    permalink: /materials/:collection/:path/
  reading:
    output: true
    category: Study Materials
    icon: book
    color: blue
    permalink: /materials/:collection/:path/
  science:
    output: true
    category: Study Materials
    icon: lightbulb_outline
    color: purple
    permalink: /materials/:collection/:path/
  social-studies:
    output: true
    category: Study Materials
    icon: account_balance
    color: green
    permalink: /materials/:collection/:path/
  writing:
    output: true
    category: Study Materials
    icon: edit
    color: red
    permalink: /materials/:collection/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: page_alt
      author: jason
      color: deep-purple
  
  # pages
  - scope:
      path: "hse"
    values:
      category: HS Equivalency Exams
  - scope:
      path: "materials"
    values:
      category: Study Materials
  - scope:
      path: "resources"
    values:
      category: Instructor Resources
  
  # instructor resources
  - scope:
      type: cde
    values:
      category: Instructor Resources
      tag: CDE
      image_path: /assets/img/cde-shield-1x.png
  - scope:
      type: curriculum
    values:
      layout: iframe
  
  # hse exams  
  - scope:
      path: "_ged"
    values:
      category: HS Equivalency Exams
      tag: GED
      tagline: Welcome to the first step towards your dreams
      image_path: /assets/img/ged-logo-1x.png
  - scope:
      path: "_hiset"
    values:
      category: HS Equivalency Exams
      tag: HiSET
      tagline: Now there’s a choice in High School Equivalency Tests
      image_path: /assets/img/hiset-logo-1x.png
  - scope:
      path: "_tasc"
    values:
      category: HS Equivalency Exams
      tag: TASC
      tagline: The New National High School Equivalency Exam
      image_path: /assets/img/tasc-logo-1x.png
      
  # materials  
  # mathematics
  - scope:
      path: "_mathematics"
    values:
      category: Study Materials
      color: orange
      icon: widgets
  - scope:
      path: "_mathematics/cc-basics"
    values:
      tag: Common Core Basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-basics/"
      image_path: /assets/img/book_covers/ccb-mathematics.jpg
  - scope:
      path: "_mathematics/cc-achieve"
    values:
      tag: Common Core Achieve
      tagline: Mastering Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-achieve/"
      image_path: /assets/img/book_covers/cca-mathematics.jpg
  - scope:
      path: "_mathematics/khan-academy"
    values:
      tag: Khan Academy
      tagline: You can learn anything!
      image_path: /assets/img/ka-logo-5x.png
  
  #reading
  - scope:
      path: "_reading"
    values:
      category: Study Materials
      color: blue
      icon: book
  - scope:
      path: "_reading/cc-basics"
    values:
      tag: Common Core Basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-basics/"
      image_path: /assets/img/book_covers/ccb-reading.jpg
  - scope:
      path: "_reading/cc-achieve"
    values:
      tag: Common Core Achieve
      tagline: Mastering Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-achieve/"
      image_path: /assets/img/book_covers/cca-reading.jpg
  - scope:
      path: "_reading/poetry"
    values:
      layout: page_2002
      tag: Poetry
      tagline: 
      source: 
      image_path: /assets/img/book_covers/cca-reading.jpg
  # science
  - scope:
      path: "_science"
    values:
      category: Study Materials
      color: purple
      icon: lightbulb_outline
      layout: article
  - scope:
      path: "_science/cc-basics"
    values:
      tag: Common Core Basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-basics/"
      image_path: /assets/img/book_covers/ccb-science.jpg
  - scope:
      path: "_science/cc-achieve"
    values:
      tag: Common Core Achieve
      tagline: Mastering Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-achieve/"
      image_path: /assets/img/book_covers/cca-science.jpg
  
  # social studies
  - scope:
      path: "_social-studies"
    values:
      category: Study Materials
      color: green
      icon: account_balance
  - scope:
      path: "_social-studies/cc-basics"
    values:
      tag: Common Core Basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-basics/"
      image_path: /assets/img/book_covers/ccb-social-studies.jpg
  - scope:
      path: "_social-studies/cc-achieve"
    values:
      tag: Common Core Achieve
      tagline: Mastering Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-achieve/"
      image_path: /assets/img/book_covers/cca-social-studies.jpg

# writing
  - scope:
      path: "_writing"
    values:
      category: Study Materials
      color: red
      icon: edit
  - scope:
      path: "_writing/cc-basics"
    values:
      tag: Common Core Basics
      tagline: Building Essential Test Readiness Skills for High School Equivalency Exams
      source: "http://www.highschoolequivalency.com/category/products/common-core-basics/"
      image_path: /assets/img/book_covers/ccb-writing.jpg